config/routes.rb
LogIt::Application.routes.draw do

	resources :books

	root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	validates :title, presence: true, length: {minimum:3, maximum: 25} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)

		if @book.save
			redirect_to @book
		else
			render 'new'
		end
	end

	def show
		@book = Book.find(params[:id])
	end

	def index
		@books = Book.all
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])

		if @book.update(book_params)
			redirect_to @book
		else
			render 'edit'
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy

		redirect_to books_path
	end

	private
		def book_params
			params.require(:book).permit(:title, :author)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
	<% if @book.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
		<ul>
		<% @article.errors.full_messages.each do |msg| %>
			<li><@= msg %></li>
		<% end %>
		</ul>
	</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :author %><br>
		<%= f.text_field :author %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<% render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<%= link_to 'New Book', new_book_path %>

<table>
	<tr>
		<th>Title</th>
		<th>Author</th>
		<th colspan="3"></th>
	</tr>

	<% @books.each do |book| %>
		<tr>
			<td><%= book.title %></td>
			<td><%= book.author %></td>
			<td><%= link_to 'Show', book_path(book) %></td>
			<td><%= link_to 'Edit', edit_book_path(book) %></td>
			<td><%= link_to 'Remove', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

app/views/books/new.html.erb
<h1>New Book</h2>

<% render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @book.title %>
</p>

<p>
	<strong>Author:</strong>
	<%= @book.author %>
</p>

<%= link_to 'Back', books_path %>
 | <%= link_to 'Edit', edit_book_path(@book) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LogIt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to LogIt</h1>
<h2>LogIt keeps track of the books, shows, movies, and games that you haven't gotten around to yet</h2>

<%= link_to 'Books', controller: 'books' %>